dic = {'bo': 'bn >> 2',
'ly': 'lf >> 1',
'fq': 'fo >> 3',
'cq': 'cj | cp',
'ga': 'fo | fz',
'u': 't | s',
'a': 'lx',
'ay': '~ax',
'hf': 'he >> 2',
'lr': 'lf | lq',
'lu': 'lr & lt',
'ek': 'dy | ej',
'cy': '1 & cx',
'hv': 'hb << 1',
'bi': '1 & bh',
'ik': 'ih & ij',
't': 'c << 1',
'ed': 'ea & eb',
'ko': 'km | kn',
'bx': '~bw',
'cu': 'ci | ct',
'q': '~p',
'lx': 'lw | lv',
'lp': '~lo',
'fw': 'fp | fv',
'r': 'o & q',
'dk': 'dh & dj',
'bj': 'ap << 1',
'ce': 'bk << 1',
'ij': '~ii',
'gj': 'gh | gi',
'ld': 'kk >> 1',
'lw': 'lc << 1',
'lc': 'lb | la',
'an': '1 & am',
'gq': 'gn & gp',
'lh': 'lf >> 3',
'g': 'e | f',
'lo': 'lg & lm',
'db': 'ci >> 1',
'cz': 'cf << 1',
'cg': 'bn >> 1',
'fg': 'et & fe',
'iu': 'iss | it',
'kz': 'kw & ky',
'cn': 'ck & cl',
'bk': 'bj | bi',
'hc': 'gj >> 1',
'jh': 'iu & jf',
'bt': '~bs',
'kw': 'kk | kv',
'kv': 'ks & ku',
'il': 'hz | ik',
'v': 'b >> 1',
'jn': 'iu >> 1',
'fr': 'fo >> 5',
'bh': 'be & bg',
'gd': 'ga & gc',
'hm': 'hf | hl',
'lf': 'ld | le',
'av': 'aas >> 5',
'fo': 'fm | fn',
'hp': 'hm & ho',
'ln': 'lg | lm',
'ky': '~kx',
'km': 'kk >> 3',
'en': 'ek & em',
'fu': '~ft',
'ji': '~jh',
'jp': 'jn | jo',
'gw': 'gj & gu',
'l': 'd & j',
'fm': 'et >> 1',
'jx': 'jq | jw',
'eq': 'ep | eo',
'lz': 'lv << 15',
'ez': '~ey',
'jq': 'jp >> 2',
'ej': 'eg & ei',
'dn': '~dm',
'kc': 'jp & ka',
'bf': 'aas & bd',
'fl': 'fk | fj',
'dy': 'dw | dx',
'lm': 'lj & ll',
'ef': 'ec & ee',
'ft': 'fq & fr',
'kq': '~kp',
'kk': 'ki | kj',
'da': 'cz | cy',
'au': 'aas >> 3',
'ar': 'an << 15',
'fn': 'fj << 15',
'fj': '1 & fi',
'hx': 'he >> 1',
'lg': 'lf >> 2',
'kj': 'kf << 15',
'eh': 'dz & ef',
'id': 'ib | ic',
'li': 'lf >> 5',
'br': 'bp | bq',
'gt': '~gs',
'gh': 'fo >> 1',
'cc': 'bz & cb',
'ec': 'ea | eb',
'ls': 'lf & lq',
'm': '~l',
'ib': 'hz >> 3',
'dj': '~di',
'll': '~lk',
'jr': 'jp >> 3',
'js': 'jp >> 5',
'bg': '~bf',
'w': 's << 15',
'fk': 'eq << 1',
'jm': 'jl | jk',
'im': 'hz & ik',
'eg': 'dz | ef',
'gz': '1 & gy',
'le': 'la << 15',
'bu': 'br & bt',
'co': '~cn',
'x': 'v | w',
'k': 'd | j',
'ge': '1 & gd',
'ih': 'ia | ig',
'gp': '~go',
'ee': '~ed',
'jy': 'jq & jw',
'ff': 'et | fe',
'az': 'aw & ay',
'fi': 'ff & fh',
'jl': 'ir << 1',
'ha': 'gg << 1',
'y': 'x >> 2',
'dd': 'db | dc',
'bn': 'bl | bm',
'ie': 'ib & ic',
'z': 'x >> 3',
'lk': 'lh & li',
'cf': 'ce | cd',
'bc': '~bb',
'hl': 'hi & hk',
'gc': '~gb',
's': '1 & r',
'fz': 'fw & fy',
'fe': 'fb & fd',
'eo': '1 & en',
'ab': 'z | aa',
'bm': 'bi << 15',
'hi': 'hg | hh',
'lb': 'kh << 1',
'ci': 'cg | ch',
'la': '1 & kz',
'gg': 'gf | ge',
'gk': 'gj >> 2',
'de': 'dd >> 2',
'lt': '~ls',
'lj': 'lh | li',
'jt': 'jr | js',
'ax': 'au & av',
'c': '0',
'hr': 'he & hp',
'ig': 'id & iff',
'ew': 'et >> 5',
'bs': 'bp & bq',
'h': 'e & f',
'ma': 'ly | lz',
'lv': '1 & lu',
'je': '~jd',
'hb': 'ha | gz',
'er': 'dy >> 1',
'iv': 'iu >> 2',
'hs': '~hr',
'bl': 'aas >> 1',
'kl': 'kk >> 2',
'p': 'b & n',
'lq': 'ln & lp',
'cr': 'cj & cp',
'do': 'dl & dn',
'cj': 'ci >> 2',
'be': 'aas | bd',
'gi': 'ge << 15',
'ic': 'hz >> 5',
'ep': 'dv << 1',
'ks': 'kl | kr',
'gv': 'gj | gu',
'hh': 'he >> 5',
'fh': '~fg',
'hj': 'hg & hh',
'o': 'b | n',
'jo': 'jk << 15',
'hd': 'gz << 15',
'dc': 'cy << 15',
'kn': 'kk >> 5',
'ck': 'ci >> 3',
'ba': 'at | az',
'iw': 'iu >> 3',
'kr': 'ko & kq',
'ei': '~eh',
'aas': 'aq | ar',
'jb': 'iy & ja',
'df': 'dd >> 3',
'bp': 'bn >> 3',
'cd': '1 & cc',
'bb': 'at & az',
'aj': 'x | ai',
'kx': 'kk & kv',
'ap': 'ao | an',
'ea': 'dy >> 3',
'aq': 'x >> 1',
'fc': 'eu & fa',
'kt': 'kl & kr',
'ii': 'ia & ig',
'di': 'df & dg',
'fy': '~fx',
'n': 'k & m',
'bq': 'bn >> 5',
'kp': 'km & kn',
'dx': 'dt << 15',
'ia': 'hz >> 2',
'am': 'aj & al',
'ch': 'cd << 15',
'he': 'hc | hd',
'hg': 'he >> 3',
'bz': 'bn | by',
'ku': '~kt',
'ac': 'z & aa',
'al': '~ak',
'cx': 'cu & cw',
'iff': '~ie',
'dz': 'dy >> 2',
'it': 'ip << 15',
'dl': 'de | dk',
'aw': 'au | av',
'jj': 'jg & ji',
'cv': 'ci & ct',
'eb': 'dy >> 5',
'hz': 'hx | hy',
'fb': 'eu | fa',
'gl': 'gj >> 3',
'gb': 'fo & fz',
'jk': '1 & jj',
'kb': 'jp | ka',
'dm': 'de & dk',
'fa': 'ex & ez',
'dh': 'df | dg',
'jc': 'iv | jb',
'aa': 'x >> 5',
'hk': '~hj',
'inn': '~im',
'gf': 'fl << 1',
'hy': 'hu << 15',
'ir': 'iq | ip',
'ix': 'iu >> 5',
'fd': '~fc',
'em': '~el',
'cm': 'ck | cl',
'ev': 'et >> 3',
'iq': 'hw << 1',
'cl': 'ci >> 5',
'jd': 'iv & jb',
'dg': 'dd >> 5',
'at': 'aas >> 2',
'jz': '~jy',
'ai': 'af & ah',
'dt': '1 & ds',
'ka': 'jx & jz',
'du': 'da << 1',
'fv': 'fs & fu',
'ki': 'jp >> 1',
'iz': 'iw & ix',
'iy': 'iw | ix',
'es': 'eo << 15',
'ey': 'ev & ew',
'bd': 'ba & bc',
'fx': 'fp & fv',
'jf': 'jc & je',
'eu': 'et >> 2',
'kh': 'kg | kf',
'jg': 'iu | jf',
'et': 'er | es',
'fp': 'fo >> 2',
'cb': '~ca',
'by': 'bv & bx',
'ao': 'u << 1',
'cp': 'cm & co',
'af': 'y | ae',
'ca': 'bn & by',
'kf': '1 & ke',
'jw': 'jt & jv',
'fs': 'fq | fr',
'el': 'dy & ej',
'kd': '~kc',
'ex': 'ev | ew',
'dp': 'dd | do',
'cw': '~cv',
'gu': 'gr & gt',
'dw': 'dd >> 1',
'gx': '~gw',
'ja': '~iz',
'ip': '1 & io',
'ah': '~ag',
'f': 'b >> 5',
'cs': '~cr',
'ke': 'kb & kd',
'ju': 'jr & js',
'ct': 'cq & cs',
'io': 'il & inn',
'jv': '~ju',
'dv': 'du | dt',
'dq': 'dd & do',
'd': 'b >> 2',
'kg': 'jm << 1',
'dr': '~dq',
'bv': 'bo | bu',
'gr': 'gk | gq',
'hq': 'he | hp',
'i': '~h',
'hn': 'hf & hl',
'gy': 'gv & gx',
'ak': 'x & ai',
'bw': 'bo & bu',
'ht': 'hq & hs',
'iss': 'hz >> 1',
'gm': 'gj >> 5',
'j': 'g & i',
'gs': 'gk & gq',
'ds': 'dp & dr',
'e': 'b >> 3',
'go': 'gl & gm',
'gn': 'gl | gm',
'ag': 'y & ae',
'hw': 'hv | hu',
'b': '1674',
'ae': 'ab & ad',
'ad': '~ac',
'hu': '1 & ht',
'ho': '~hn'}
